### ISSUE TITLE
Unsorted option should have a better name

### ISSUE THREAD

**Issue by opsaaaaa** [olibia/inkscape-generate-palette#10]
I believe it sorts the colors in the order the color objects occur in the document.
This is useful functionality.

![2021-04-15_19-48](https://user-images.githubusercontent.com/5777735/114961966-19e0ad00-9e27-11eb-9a25-c41fa08fb80c.png)

so I think renaming `unsorted` to something like `Document Order` or `Object order` or `Index Order` would make it more clear.

**Comment by olibia** [comment]
@opsaaaaa I agree, it should have a better name. Thanks for the PR, too. 

`unsorted` actually does two things. If you select all the objects together, the colors are sorted by the object order/z index. But if you want a custom order and select the objects one by one, they will be sorted by the order of the selection and the object order will be ignored.

So, I think `Z index` excludes the selection order, and maybe `Default`, `Selection/Z Index` or `Selection/Object order` are better options. What do you think?

**Comment by opsaaaaa** [comment]
Good to know, I like `Selection/Z-index`.
