### ISSUE TITLE
Output palette auto arranges colour

### ISSUE THREAD

**Issue by meetdilip** [olibia/inkscape-generate-palette#3]
Please see the stacked colours using which I generated the included Palette. Both have a different order in which colours are arranged. Is it possible to get an output with the same stack order we have chosen ? Is there any correction we need to do with the current setup ?

![Screenshot from 2019-10-09 20-52-24](https://user-images.githubusercontent.com/6965443/66495563-0b4d6300-ead7-11e9-8401-94e6bcf0de94.png)

I think, when the last time I tried, it went with the stacked colour order than auto arrange. I am using Ubuntu 18.04.

@olibia 

I have attached the .gpl file as zip.

[Halloween-Colours.gpl.zip](https://github.com/olibia/inkscape-generate-palette/files/3708274/Halloween-Colours.gpl.zip)

**Comment by olibia** [comment]
Hi @meetdilip, can you try using the extension file from master branch? 

You can achieve what you want by creating the items in the order you want them in the palette. 

If you have already created them in mixed order, you can select the items one by one in the order you want them in the palette. 

Let me know if this works for you.

**Comment by meetdilip** [comment]
Thanks @olibia . I will try the files from the master branch.

I see. I created them and rearranged them to match the colour tone. I thought it will follow the stack order. Let me try once again by selecting them individually. Will update here :)

Update : 

It worked

![Screenshot from 2019-10-11 13-44-49](https://user-images.githubusercontent.com/6965443/66635954-d43d9580-ec2d-11e9-8240-bb89c9c0a246.png)
