### ISSUE TITLE
Support for 1.0

### ISSUE THREAD

**Issue by meetdilip** [olibia/inkscape-generate-palette#4]
Hi, I am a fan of this extension. Sadly it does not work in 1.0. It would be great if you can come up with a fix. Thanks.

**Comment by olibia** [comment]
Hi @meetdilip, I just published a new version with Inkscape 1.0 support. You can download the latest version [here](https://github.com/olibia/inkscape-generate-palette/releases/tag/v3.0) or from [Inkscape extensions](https://inkscape.org/~olibia/%E2%98%85generate-palette-extension).

**Comment by meetdilip** [comment]
@olibia You are awesome :)
