### ISSUE TITLE
How to install python2-lxml?

### ISSUE THREAD

**Issue by jimiblender** [olibia/inkscape-generate-palette#5]
I have been trying to create a palette in Inkscape and the extension is recognised, but I think I may have a python2-lxml issue. If I go to Extensions-Palette-Generate and select a few objects then click Apply, I get the following error:

generate_palette.py:15: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()
generate_palette.py:30: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-n', '--name', action='store', type='string', dest='name', help='Palette name')
generate_palette.py:31: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-p', '--property', action='store', type='string', dest='property', help='Color property')
generate_palette.py:32: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-d', '--default', action='store', type='inkbool', dest='default', help='Default grays')
generate_palette.py:33: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('-r', '--replace', action='store', type='inkbool', dest='replace', help='Replace existing')
generate_palette.py:139: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  palette.affect()
generate_palette.py:84: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  selected = list(self.selected.items())
generate_palette.py:69: DeprecationWarning: simplestyle.parseStyle -> dict(inkex.Style.parse_str(s))
  style = simplestyle.parseStyle(node.attrib['style'])
generate_palette.py:77: DeprecationWarning: simplestyle.parseColor -> inkex.Color(c).to_rgb()
  rgb = simplestyle.parseColor(color)
Traceback (most recent call last):
  File "generate_palette.py", line 139, in <module>
    palette.affect()
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "generate_palette.py", line 120, in effect
    self.selected_colors = self.get_selected_colors()
  File "generate_palette.py", line 101, in get_selected_colors
    return list(map(self.get_formatted_color, colors))
  File "generate_palette.py", line 77, in get_formatted_color
    rgb = simplestyle.parseColor(color)
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/deprecated.py", line 257, in _inner
    return func(*args, **kwargs)
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/deprecated-simple/simplestyle.py", line 27, in parseColor
    return tuple(inkex.Color(c).to_rgb())
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/colors.py", line 229, in __init__
    space, color = self.parse_str(color.strip())
  File "/snap/inkscape/7627/share/inkscape/extensions/inkex/colors.py", line 300, in parse_str
    raise ColorIdError("Gradient other referenced element id.")
inkex.colors.ColorIdError: 'Gradient other referenced element id.'

I'm a designer, not a developer, so I actually have no idea what any of that means. 
Any suggestions would be amazing!

**Comment by olibia** [comment]
Hi @jimiblender. Thanks for reporting this, it should be fixed in the latest version which has support for Inkscape 1.0. You can download the latest version [here](https://github.com/olibia/inkscape-generate-palette/releases/tag/v3.0) or from [Inkscape extensions](https://inkscape.org/~olibia/%E2%98%85generate-palette-extension).
