### ISSUE TITLE
Unable to generate palette

### ISSUE THREAD

**Issue by meetdilip** [olibia/inkscape-generate-palette#6]
Hi, sorry to bother you. Looks like 1.0.1 update broke this extension. When I try to generate a palette, it says

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "generate_palette.py", line 157, in <module>
    palette.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "generate_palette.py", line 139, in effect
    self.selected_colors = self.get_selected_colors()
  File "generate_palette.py", line 105, in get_selected_colors
    selected.sort(key=self.get_node_index)
  File "generate_palette.py", line 93, in get_node_index
    return self.options.ids.index(id)
ValueError: '/*/*[4]/*[1]' is not in list
```

> Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate that the result may not be as expected.

It would be nice if you can do anything on this. Thanks.

**Comment by olibia** [comment]
Hi @meetdilip, no problem! Could you give me some additional info about this error? 

- Inkscape version
- Operating System
- Steps to reproduce
 
Did you set a custom ID to any of the selected objects?

**Comment by meetdilip** [comment]
No, I didn't set any custom ID. But I am using custom `class:warning` to colour Inkscape's internal icons. Other than that, those are a few rectangles I duplicated from the first one and changed the fill. Thanks.

Inkscape 1.0.1 (1.0.1+r73)

OS : Ubuntu 20.04 with Kubuntu Desktop

I am attaching the file from which I was trying to create a palette. I hope you will be able to reproduce the error

[dusk colour scheme.zip](https://github.com/olibia/inkscape-generate-palette/files/5210916/dusk.colour.scheme.zip)

**Comment by olibia** [comment]
@meetdilip The issue should be fixed with the latest commit. 
You can install the extension manually from the master branch.

**Comment by meetdilip** [comment]
Working fine now. Was the issue related to the 1.0.1 update ? Thanks.

**Comment by olibia** [comment]
Great! It was related to the update, there was a change in the selected items list structure.
